### ISSUE TITLE
Access to panopto lectures

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2016#1]
> I have been trying to access the HPCE lecture on panopto. It does not
> seem to be available. Do I need to join a particular group before I am
> able to view the recording?

**Comment by m8pple** [comment]
By default it is only available to people who have registered
for the course, but I manually opened it up to anyone who
can login. So if you can login to panopto, you should be able
to see it - in theory, at least :)

Could you be more precise about "It does not seem to be available"?:
- Can you see the folder, or is it missing?
- Can you see other panopto'd lectures for other courses?
- Are you following a particular link, or searching for it?

**Comment by pm1113** [comment]
I have registered for the course using the online EEE portal and joined the blackboard group. 

It seems to be working now.

**Comment by m8pple** [comment]
Hrmm, might be a temporary blip.

Oh well. I'll close this for now.
