### ISSUE TITLE
Lecture 2

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2016#3]
`- [Lecture 2 : TBB details](slides/hpce-lec1-parfor-tbb.pdf)` should be 
`- [Lecture 2 : TBB details](slides/hpce-lec2-parfor-tbb.pdf)`

**Comment by m8pple** [comment]
Ah, thanks. I should really build a bot to check links.

**Comment by OJFord** [comment]
> I should really build a bot to check links.

I'm pretty sure `pandoc` will attempt to resolve links? Pretty good all-round linting with `--to=markdown --columns=80`.
